# Generated by Django 5.0.14 on 2026-08-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearingschedule',
            name='collision_warning',
            field=models.BooleanField(default=False),
        ),
    ]
