# Generated by Django 5.0.14 on 2026-08-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_hearingschedule_collision_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
